version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080" 
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
